#!/usr/bin/env python2
# -*- encoding: utf-8 -*-
from os import path
from wordcloud import WordCloud

words = [
    (u'#!/bin/bash', 2),
    (u'#!/bin/sh', 3),
    (u'#!/usr/bin/env python', 2),
    (u'#!/usr/bin/perl -w', 2),
    (u'#ifdef DEBUG', 1),
    (u'!', 3),
    (u'|', 3),
    (u'+', 3),
    (u'-', 3),
    (u'.bashrc', 3),
    (u'.emacs', 4),
    (u'.zshrc', 3),
    (u'/etc', 5),
    (u'/etc/init.d/sshd', 2),
    (u'/etc/init.d/httpd', 2),
    (u'/etc/init.d/ftpd', 2),
    (u'/etc/init.d/ntpd', 2),
    (u'/etc/init.d/bos', 2),
    (u'/etc/passwd', 4),
    (u'/etc/rc.conf', 3),
    (u'/opt/local', 3),
    (u'/usr', 4),
    (u'/usr/home', 3),
    (u'/usr/local', 3),
    (u'/var', 4),
    (u'/var/log', 3),
    (u'1978', 5),
    (u'64', 4),
    (u'64', 3),
    (u'6502', 3),
    (u'68k', 5),
    (u'8', 3),
    (u':-)', 4),
    (u';-)', 4),
    (u'?', 3),
    (u'AFS', 9),
    (u'AFS', 5),
    (u'AFS', 3),
    (u'ARM', 5),
    (u'AUTOEXEC.BAT', 1),
    (u'AlexMUD', 2),
    (u'Android', 7),
    (u'Arduino', 4),
    (u'Arla', 6),
    (u'BIOS', 4),
    (u'BSD 4.3', 5),
    (u'Baltikumprojektet', 3),
    (u'Berkley Source Distribution', 3),
    (u'BitTorrent', 3),
    (u'C++', 10),
    (u'CPU', 7),
    (u'Cascading Style Sheets', 2),
    (u'Centos', 7),
    (u'Chrome', 4),
    (u'Coca Cola', 6),
    (u'Common Lisp', 4),
    (u'DEC', 5),
    (u'DIGITAL', 7),
    (u'DNS', 12),
    (u'Debian', 9),
    (u'Donald Knuth', 6),
    (u'ETLA', 5),
    (u'Fedora', 9),
    (u'Firefox', 6),
    (u'FreeBSD', 9),
    (u'FreeType', 3),
    (u'GLFW', 6),
    (u'GNU on VMS', 2),
    (u'GNU', 11),
    (u'HTTP/2', 8),
    (u'Hacker', 3),
    (u'HashMap', 3),
    (u'HyperText Transfer Protocol', 2),
    (u'HyperText Markup Language', 2),
    (u'I/O', 5),
    (u'IPMI', 3),
    (u'IPv4', 7),
    (u'IPv6', 9),
    (u'ISO-8859-1', 2),
    (u'ISO-8859-15', 2),
    (u'Java', 5),
    (u'KTH', 17),
    (u'Kerberos', 14),
    (u'LAN', 5),
    (u'Linux', 16),
    (u'Linux', 10),
    (u'Linux', 6),
    (u'Linux', 2),
    (u'Mountain Dew', 4),
    (u'NetBSD', 5),
    (u'OSX', 9),
    (u'Open Source', 13),
    (u'OpenBSD', 8),
    (u'OpenGL', 6),
    (u'OpenSSL', 7),
    (u'OpenType', 3),
    (u'OpenVMS', 5),
    (u'Out of band management', 1),
    (u'PDF', 8),
    (u'PDP/11', 6),
    (u'PostIt', 4),
    (u'Q', 16),
    (u'Q-huset', 11),
    (u'RHEL', 5),
    (u'Raspberry Pi', 4),
    (u'Ruby', 10),
    (u'Rust', 10),
    (u'SATA', 6),
    (u'SCSI', 6),
    (u'SIP', 4),
    (u'SQL', 10),
    (u'Solaris', 6),
    (u'Stacken', 12),
    (u'Stacken', 40),
    (u'Stackenföreläsning', 16),
    (u'Stackpointer', 5),
    (u'Stockholm', 10),
    (u'Sun', 5),
    (u'TCP/IP', 5),
    (u'THS', 8),
    (u'TLA', 5),
    (u'Tcl/Tk', 2),
    (u'Tekniska Högskolans Studentkår', 5),
    (u'The Art of Computer Programming', 2),
    (u'Torsdag', 25),
    (u'TreeMap', 5),
    (u'Tru64', 5),
    (u'TrueType', 3),
    (u'Ubuntu', 5),
    (u'UNIX Network Programming', 2),
    (u'Unix System V', 3),
    (u'Unix', 19),
    (u'VMS', 5),
    (u'Vax', 5),
    (u'WAN', 5),
    (u'WPA', 6),
    (u'Webkit', 3),
    (u'Wikipedia', 5),
    (u'Windows', 7),
    (u'X', 5),
    (u'X11', 5),
    (u'X11R6', 7),
    (u'YXA', 4),
    (u'abstraktion', 7),
    (u'assembler', 5),
    (u'atomklocka', 3),
    (u'automake', 1),
    (u'autoconf', 1),
    (u'awk', 3),
    (u'bash', 5),
    (u'binary', 3),
    (u'bit', 3),
    (u'bitar', 2),
    (u'block', 3),
    (u'blockrepresentation', 2),
    (u'byte', 5),
    (u'c', 5),
    (u'c++', 7),
    (u'carbon', 5),
    (u'cargo run', 3),
    (u'ceph', 7),
    (u'cisco', 5),
    (u'clojure', 5),
    (u'closure', 5),
    (u'cluster', 7),
    (u'code', 14),
    (u'command', 5),
    (u'compiler', 7),
    (u'couchdb', 4),
    (u'csh', 5),
    (u'css', 9),
    (u'cvs', 4),
    (u'damm', 1),
    (u'dator', 5),
    (u'datorer', 7),
    (u'datorarkeologi', 6),
    (u'datorförening', 16),
    (u'datorförening', 12),
    (u'datorhall', 15),
    (u'datorhall', 11),
    (u'demoprogrammering', 7),
    (u'device', 5),
    (u'diskchassi', 5),
    (u'diskuterar', 5),
    (u'docker', 7),
    (u'elixir', 6),
    (u'emacs', 9),
    (u'eps', 5),
    (u'erlang', 5),
    (u'fil', 5),
    (u'fish', 4),
    (u'foo bar baz', 1),
    (u'foo bar', 2),
    (u'foo', 3),
    (u'fork()', 4),
    (u'fprintf()', 4),
    (u'fulhack', 2),
    (u'funktionell programmering', 3),
    (u'fågelbur', 2),
    (u'git', 9),
    (u'github', 8),
    (u'glusterfs', 7),
    (u'grep', 5),
    (u'groff', 5),
    (u'h2o', 5),
    (u'hack', 5),
    (u'haskell', 4),
    (u'heimdal', 15),
    (u'html', 7),
    (u'html5', 7),
    (u'http', 6),
    (u'https', 6),
    (u'hårddisk', 6),
    (u'hårdvara', 14),
    (u'höstmöte', 5),
    (u'iOS', 5),
    (u'imap', 7),
    (u'int main(argc, argv)', 3),
    (u'int', 5),
    (u'interface', 5),
    (u'internet', 10),
    (u'java', 7),
    (u'javascript', 6),
    (u'jpeg', 5),
    (u'json', 5),
    (u'kaffe', 12),
    (u'katalog', 5),
    (u'kerberos', 16),
    (u'klient', 5),
    (u'kompilator', 11),
    (u'kryptografi', 9),
    (u'kvantdator', 5),
    (u'kylskåp', 11),
    (u'kårförening', 7),
    (u'kårförening', 3),
    (u'language', 5),
    (u'lekstugan', 5),
    (u'lisp', 8),
    (u'lokal', 12),
    (u'machine', 5),
    (u'main()', 7),
    (u'make install', 3),
    (u'make world', 4),
    (u"make: don't know how to make love. Stop.", 1),
    (u'minecraft', 3),
    (u'minne', 5),
    (u'mkdir', 3),
    (u'monotone', 5),
    (u'mp3', 5),
    (u'mud', 5),
    (u'mysql', 8),
    (u'netvärk', 1),
    (u'node.js', 5),
    (u'nosql', 4),
    (u'nroff', 5),
    (u'ntp', 8),
    (u'nuccc', 4),
    (u'nätverk', 5),
    (u'obegripligt', 1),
    (u'obfuskerad', 5),
    (u'objektorienterad', 5),
    (u'ogg', 5),
    (u'operativsystem', 15),
    (u'optimering', 5),
    (u'packa', 5),
    (u'papegoja', 5),
    (u'parrot', 5),
    (u'pdf', 5),
    (u'pdp', 9),
    (u'perl', 6),
    (u'pipe()', 5),
    (u'png', 5),
    (u'postfix', 11),
    (u'postgresql', 9),
    (u'postscript', 7),
    (u'prestanda', 5),
    (u'primtal', 5),
    (u'processor', 7),
    (u'programmering', 15),
    (u'ps', 5),
    (u'python', 9),
    (u'rackmontering', 7),
    (u'raytracer', 5),
    (u'rcs', 5),
    (u'REST', 5),
    (u'rekursion', 10),
    (u'rekursion, se rekursion', 2),
    (u'rollup', 3),
    (u'router', 6),
    (u'rtfm', 2),
    (u'ruby', 7),
    (u'rust', 7),
    (u'scheme', 5),
    (u'sed', 5),
    (u'segvara', 5),
    (u'sendmail.cf', 4),
    (u'server', 9),
    (u'sh', 5),
    (u'showpage', 4),
    (u'soffa', 16),
    (u'sort', 5),
    (u'source', 5),
    (u'ssh', 10),
    (u'stacken@stacken.kth.se', 14),
    (u'stackomaten', 14),
    (u'storage', 5), 
    (u'styrelsen@stacken.kth.se', 3),
    (u'sushi', 8),
    (u'swift', 5),
    (u'systemadministration', 8),
    (u'te', 5),
    (u'textigenkänning', 5),
    (u'tiff', 5),
    (u'troff', 5),
    (u'trådlös', 5),
    (u'utf8', 5),
    (u'ux', 5),
    (u'vi', 5),
    (u'vim', 9),
    (u'virtualisering', 5),
    (u'vmware', 5),
    (u'void', 5),
    (u'vorbis', 5),
    (u'vårmöte', 5),
    (u'web', 5),
    (u'whiteboard', 5),
    (u'wiki', 5),
    (u'www.Stacken.KTH.se', 17),
    (u'x86', 5),
    (u'xml', 5),
    (u'zones', 5),
    (u'zsh', 6),
]

#bigsize = 1
#allwords = words
# Snyggare, men _mycket_ tyngre att rita.
bigsize = 15;
allwords = [(w, s*20) for w, s in words] + \
           [(w, s*8) for w, s in words] + \
           [(w, s*7) for w, s in words] + \
           [(w, s*6) for w, s in words] + \
           [(w, s*6) for w, s in words] + \
           [(w, s*5) for w, s in words] + \
           [(w, s*5) for w, s in words] + \
           [(w, s*4) for w, s in words] + \
           [(w, s*4) for w, s in words] + \
           [(w, s*4) for w, s in words] + \
           [(w, s*4) for w, s in words]

print "Making a cloud of %d words." % len(allwords)

s = 4 * bigsize
wordcloud = WordCloud(width=60*s, height=200*s, max_font_size=18 * s,
                      font_path='/usr/share/fonts/sil-gentium-basic/GenBkBasR.ttf',
                      min_font_size=3*bigsize,
                      max_words=len(allwords), stopwords=[],
                      relative_scaling=0.8).fit_words(allwords)

image = wordcloud.to_image()
image.save('image.png')
